package org.greencloud.agentsystem.strategies.domain;

public class EGCSRuleSetTypes {

	public static final String EXECUTION_TIME_PRIORITIZATION_RULE_SET = "EXECUTION_TIME_PRIORITIZATION_RULE_SET";
	public static final String STRATEGY_BASE_TWO_STEP_ALLOCATION_RULE_SET = "STRATEGY_BASE_TWO_STEP_ALLOCATION_RULE_SET";
	public static final String STRATEGY_BASE_ONE_STEP_ALLOCATION_RULE_SET = "STRATEGY_BASE_ONE_STEP_ALLOCATION_RULE_SET";

	public static final String INTENT_BASED_ONE_STEP_ALLOCATION_RULE_SET = "INTENT_BASED_ONE_STEP_ALLOCATION_RULE_SET";
}
